controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    t170_controller:
      type: ros2_control_t170/RobotController


t170_controller:
  ros__parameters:
    joints:
      - r_arm_joint1
      - r_arm_joint2
      - R_SHOULDER_R
      - R_SHOULDER_Y
      - l_arm_joint1
      - l_arm_joint2
      - L_SHOULDER_R
      - L_SHOULDER_Y
      - leg_r1_joint
      - leg_r2_joint
      - leg_r3_joint
      - leg_r4_joint
      - leg_r5_joint
      - leg_r6_joint
      - leg_l1_joint
      - leg_l2_joint
      - leg_l3_joint
      - leg_l4_joint
      - leg_l5_joint
      - leg_l6_joint
      - WAIST_Y
      - WAIST_P
      - WAIST_R
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    # RL 配置参数
    init_state:
      default_joint_angle:
        leg_l1_joint: 0.0
        leg_l2_joint: 0.0
        leg_l3_joint: 0.0
        leg_l4_joint: 0.0
        leg_l5_joint: 0.0
        leg_l6_joint: 0.0
        leg_r1_joint: 0.0
        leg_r2_joint: 0.0
        leg_r3_joint: 0.0
        leg_r4_joint: 0.0
        leg_r5_joint: 0.0
        leg_r6_joint: 0.0
        l_arm_joint1: 0.0
        l_arm_joint2: 0.0
        r_arm_joint1: 0.0
        r_arm_joint2: 0.0
    control:
      stiffness:
        leg_l1_joint: 50.0
        leg_l2_joint: 50.0
        leg_l3_joint: 50.0
        leg_l4_joint: 50.0
        leg_l5_joint: 50.0
        leg_l6_joint: 50.0
        leg_r1_joint: 50.0
        leg_r2_joint: 50.0
        leg_r3_joint: 50.0
        leg_r4_joint: 50.0
        leg_r5_joint: 50.0
        leg_r6_joint: 50.0
        l_arm_joint1: 30.0
        l_arm_joint2: 30.0
        r_arm_joint1: 30.0
        r_arm_joint2: 30.0
        R_SHOULDER_R: 20.0
        R_SHOULDER_Y: 20.0
        L_SHOULDER_R: 20.0
        L_SHOULDER_Y: 20.0
        WAIST_Y: 10.0
        WAIST_P: 10.0
        WAIST_R: 10.0
      damping:
        leg_l1_joint: 5.0
        leg_l2_joint: 5.0
        leg_l3_joint: 5.0
        leg_l4_joint: 5.0
        leg_l5_joint: 5.0
        leg_l6_joint: 5.0
        leg_r1_joint: 5.0
        leg_r2_joint: 5.0
        leg_r3_joint: 5.0
        leg_r4_joint: 5.0
        leg_r5_joint: 5.0
        leg_r6_joint: 5.0
        l_arm_joint1: 3.0
        l_arm_joint2: 3.0
        r_arm_joint1: 3.0
        r_arm_joint2: 3.0
        R_SHOULDER_R: 2.0
        R_SHOULDER_Y: 2.0
        L_SHOULDER_R: 2.0
        L_SHOULDER_Y: 2.0
        WAIST_Y: 1.0
        WAIST_P: 1.0
        WAIST_R: 1.0
      action_scale: 0.5
      decimation: 20
      cycle_time: 1.2
    normalization:
      clip_scales:
        clip_observations: 100.0
        clip_actions: 100.0
      obs_scales:
        lin_vel: 2.0
        ang_vel: 1.0
        dof_pos: 1.0
        dof_vel: 0.05
        height_measurements: 5.0
        quat: 1.0
    size:
      num_hist: 66
      actions_size: 12
      observations_size: 47
    mode:
      sw_mode: true
      cmd_threshold: 0.05