controller_manager:
  ros__parameters:
    update_rate:  200 #HZ

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    t170_controller:
      type: ros2_control_t170/RobotController

t170_controller:
  ros__parameters:
    joints:
      - leg_l1_joint    # ID 7
      - leg_l2_joint    # ID 8
      - leg_l3_joint    # ID 9
      - leg_l4_joint    # ID 10
      - leg_l5_joint    # ID 11
      - leg_l6_joint    # ID 12
      - leg_r1_joint    # ID 1
      - leg_r2_joint    # ID 2
      - leg_r3_joint    # ID 3
      - leg_r4_joint    # ID 4
      - leg_r5_joint    # ID 5
      - leg_r6_joint    # ID 6
      - l_arm_joint1    # ID 23
      - l_arm_joint2    # ID 26
      - r_arm_joint1    # ID 16
      - r_arm_joint2    # ID 19


    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    # RL 配置参数
    joint_offsets:
      joint_1: 0.0
      joint_2: 0.0
      joint_3: 0.0
      joint_4: 0.0
      joint_5: 0.0
      joint_6: 0.0
      joint_7: 0.0
      joint_8: 0.0
      joint_9: 0.0
      joint_10: 0.0
      joint_11: 0.0
      joint_12: 0.0
      joint_13: 0.0
      joint_14: 0.0
      joint_15: 0.0
      joint_16: 0.0
    init_state:
      default_joint_angle:
        leg_l1_joint: -0.0
        leg_l2_joint: -0.0
        leg_l3_joint: -0.1
        leg_l4_joint: 0.1
        leg_l5_joint: -0.0
        leg_l6_joint: -0.0
        leg_r1_joint: -0.0
        leg_r2_joint: -0.0
        leg_r3_joint: -0.1
        leg_r4_joint: 0.1
        leg_r5_joint: -0.0
        leg_r6_joint: -0.0
        l_arm_joint1: 0.0
        l_arm_joint2: 0.0
        r_arm_joint1: 0.0
        r_arm_joint2: 0.0
    control:
      stiffness:
        leg_l1_joint: 50.0
        leg_r1_joint: 50.0
        leg_l2_joint: 60.0
        leg_r2_joint: 60.0
        leg_l3_joint: 90.0
        leg_r3_joint: 90.0
        leg_l4_joint: 120.0
        leg_r4_joint: 120.0
        leg_l5_joint: 120.0
        leg_r5_joint: 120.0
        leg_l6_joint: 30.0
        leg_r6_joint: 30.0
        l_arm_joint1: 70.0
        l_arm_joint2: 70.0
        r_arm_joint1: 70.0
        r_arm_joint2: 70.0
        R_SHOULDER_R: 20.0
        R_SHOULDER_Y: 20.0
        L_SHOULDER_R: 20.0
        L_SHOULDER_Y: 20.0
        WAIST_Y: 10.0
        WAIST_P: 10.0
        WAIST_R: 10.0
      damping:
        leg_l1_joint: 5.0
        leg_r1_joint: 5.0
        leg_l2_joint: 6.0
        leg_r2_joint: 6.0
        leg_l3_joint: 9.0
        leg_r3_joint: 9.0
        leg_l4_joint: 12.0
        leg_r4_joint: 12.0
        leg_l5_joint: 12.0
        leg_r5_joint: 12.0
        leg_l6_joint: 3.0
        leg_r6_joint: 3.0
        l_arm_joint1: 3.0
        l_arm_joint2: 3.0
        r_arm_joint1: 3.0
        r_arm_joint2: 3.0
        R_SHOULDER_R: 2.0
        R_SHOULDER_Y: 2.0
        L_SHOULDER_R: 2.0
        L_SHOULDER_Y: 2.0
        WAIST_Y: 1.0
        WAIST_P: 1.0
        WAIST_R: 1.0
      action_scale: 0.5
      decimation: 2
      cycle_time: 0.8  #1.1
    normalization:
      clip_scales:
        clip_observations: 100.0
        clip_actions: 100.0
      obs_scales:
        lin_vel: 2.0
        ang_vel: 1.0
        dof_pos: 1.0
        dof_vel: 0.05
        height_measurements: 5.0
        quat: 1.0
    size:
      num_hist: 66
      actions_size: 12
      observations_size: 47
    mode:
      sw_mode: true
      cmd_threshold: 0.05
